IF EXISTS (SELECT 1 FROM SYS.objects WHERE TYPE = 'TR' AND NAME = 'TRG_ATIVAR_PROCEDURES')
	BEGIN
		DROP TRIGGER TRG_ATIVAR_PROCEDURES
	END
GO


CREATE TRIGGER TRG_ATIVAR_PROCEDURES
ON Carga
FOR INSERT
AS
BEGIN

	EXEC CARREGAR_CLIENTES
	EXEC CARREGAR_PRODUTOS
	EXEC CARREGAR_PEDIDOS
	EXEC CARREGAR_iTENS_PEDIDOS	

END
GO
