IF EXISTS (SELECT 1 FROM SYS.objects WHERE TYPE = 'P' AND NAME = 'CARREGAR_CLIENTES')
	BEGIN
		DROP PROCEDURE CARREGAR_CLIENTES
	END
GO

CREATE PROCEDURE CARREGAR_CLIENTES
AS
BEGIN
	INSERT INTO Cliente (Nome, CPF, Email) SELECT DISTINCT CA.Nome_Comprador, CA.CPF, CA.Email FROM Carga CA
	LEFT JOIN Cliente CL ON (CL.Email = CA.Email) WHERE ISNULL(CL.Nome,'')=''
	/*SE O NOME QUE RECEBE DO "ON" NAO EXISTIR NA TABELA CLIENTE A FUNCAO RETORNA ('') E NISSO O WHERE DA TRUE, MAS SE O NOME EXISTIR
	O WHERE VAI DAR FALSE PQ NOME != ('')*/
END
GO


IF EXISTS (SELECT 1 FROM SYS.objects WHERE TYPE = 'P' AND NAME = 'CARREGAR_PRODUTOS')
	BEGIN
		DROP PROCEDURE CARREGAR_PRODUTOS
	END
GO

CREATE PROCEDURE CARREGAR_PRODUTOS
AS
BEGIN
	INSERT INTO Produto (ID_Produto, Valor, Nome_produto, Frete_Produto, UPC) SELECT DISTINCT
	CA.ID_Produto, CA.Valor, CA.Nome_Produto, CA.Frete, CA.UPC FROM Carga CA LEFT JOIN Produto PD ON (PD.ID_Produto=CA.ID_Produto)
	WHERE ISNULL(PD.ID_Produto,'')='' AND CA.UPC <> ALL (SELECT UPC FROM Produto)
END
GO




IF EXISTS (SELECT 1 FROM SYS.objects WHERE TYPE = 'P' AND NAME = 'CARREGAR_PEDIDOS')
	BEGIN
		DROP PROCEDURE CARREGAR_PEDIDOS
	END
GO

CREATE PROCEDURE CARREGAR_PEDIDOS
AS
BEGIN
	INSERT INTO Pedido (ID_Pedido, Data_Pedido, Quant_Produto, Endereco_Pedido, CEP, UF, PAIS, ID_Cliente) SELECT DISTINCT
	CA.ID_Pedido, CONVERT(DATE, CA.Pedido_data, 23), CA.Quant, CA.Endereco, CA.CEP, CA.UF, CA.PAIS, CL.ID_cliente FROM Carga CA INNER JOIN Cliente CL ON (CL.Email=CA.Email)
	LEFT JOIN Pedido PE ON (PE.ID_Pedido=CA.ID_Pedido) WHERE ISNULL(PE.ID_Pedido, '')=''
END
GO


IF EXISTS (SELECT 1 FROM SYS.objects WHERE TYPE = 'P' AND NAME = 'CARREGAR_iTENS_PEDIDOS')
	BEGIN
		DROP PROCEDURE CARREGAR_iTENS_PEDIDOS
	END
GO

CREATE PROCEDURE CARREGAR_iTENS_PEDIDOS
AS
BEGIN
	INSERT INTO Itens_Pedidos (ID_Produto, ID_Pedido, Quant) SELECT DISTINCT CA.ID_Produto, CA.ID_Pedido, CA.Quant
	FROM Carga CA LEFT JOIN Itens_Pedidos IT ON (IT.ID_Produto=CA.ID_Produto) WHERE ISNULL(IT.ID_Produto, '')=''
END
GO






 
