SELECT * FROM Carga 

SELECT * FROM Cliente
SELECT * FROM Produto 
SELECT * FROM Pedido
SELECT * FROM Itens_Pedidos
SELECT * FROM Movimentação_Estoque
SELECT * FROM Compras

DELETE FROM Carga
DELETE FROM Itens_Pedidos DELETE FROM Compras DELETE FROM Movimentação_Estoque DELETE FROM Produto DELETE FROM Pedido DELETE FROM Cliente

--DROP TABLE Carga 
DROP TABLE Itens_Pedidos DROP TABLE Compras DROP TABLE Movimentação_Estoque DROP TABLE Produto DROP TABLE Pedido DROP TABLE Cliente

EXEC CARREGAR_CLIENTES
EXEC CARREGAR_PRODUTOS
EXEC CARREGAR_PEDIDOS
EXEC CARREGAR_iTENS_PEDIDOS
EXEC MOVIMENTAR_ESTOQUE

